---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get booklogr db container state
      community.docker.docker_container:
        name: "{{ booklogr_db_container_name }}"
      register: result_db

    - name: Get booklogr auth db container state
      community.docker.docker_container:
        name: "{{ booklogr_auth_db_container_name }}"
      register: result_auth_db

    - name: Get booklogr api container state
      community.docker.docker_container:
        name: "{{ booklogr_api_container_name }}"
      register: result_api

    - name: Get booklogr auth api container state
      community.docker.docker_container:
        name: "{{ booklogr_auth_api_container_name }}"
      register: result_auth_api

    - name: Get booklogr web container state
      community.docker.docker_container:
        name: "{{ booklogr_web_container_name }}"
      register: result_web

    - name: Check if booklogr containers are running
      ansible.builtin.assert:
        that:
          - result_db.container['State']['Status'] == "running"
          - result_db.container['State']['Restarting'] == false
          - result_auth_db.container['State']['Status'] == "running"
          - result_auth_db.container['State']['Restarting'] == false
          - result_api.container['State']['Status'] == "running"
          - result_api.container['State']['Restarting'] == false
          - result_auth_api.container['State']['Status'] == "running"
          - result_auth_api.container['State']['Restarting'] == false
          - result_web.container['State']['Status'] == "running"
          - result_web.container['State']['Restarting'] == false
