---
roles:
  - name: geerlingguy.docker
    version: 2.8.2

  - name: bertvv.samba
    version: v2.7.1

  - name: geerlingguy.nfs
    version: 1.6.0

  - name: stefangweichinger.ansible_rclone

  - name: tigattack.mergerfs

  - name: arillso.restic
