#!/bin/bash

exec &> /dev/null #Hide output

Pushover_URL='{{ pushover_url }}'
Pushover_Token='{{ pushover_token }}'
Pushover_User_Key='{{ pushover_user_key }}'

notify()
{

        now=$(date -d "-60 seconds" +%s) #Get current time minus 60 seconds
        end=$((SECONDS+30)) #Set 30s Timeout for loop

        while [ $SECONDS -lt $end ]; do

                SSHdate=$(date -d "$(who |grep pts|tail -1 | awk '{print $3, $4}')" +%s) #Check for the latest SSH session

                if [ $SSHdate -ge $now ]; then #Once who is updated continue with sending Notification

                        title="SSH Login for $(/bin/hostname -f)"
                        message="$(/usr/bin/who | grep pts)"

                        /usr/bin/curl -X POST -s \
                                --form-string "token=${Pushover_Token}" \
                                --form-string "user=${Pushover_User_Key}" \
                                --form-string "message=${message}" \
                                --form-string "title=${title}" \
                                "${Pushover_URL}"

                        break
                fi
        done

}

notify & #Run in background to prevent holding up the login process