---
- name: Prepare
  hosts: all
  tasks:
    - name: Install docker python module
      community.general.pipx:
        name: "{{ item }}"
      with_items:
        - docker
        - urllib3<2
        - molecule-plugins[docker]
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true
      register: result
      until: result is succeeded
