---
- name: Prepare
  hosts: all
  tasks:
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true
      register: result
      until: result is succeeded
