---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        ansible.builtin.file: ../../defaults/main.yml

    - name: Get barcodebuddy container state
      docker_container_info:
        name: "{{ barcodebuddy_container_name }}"
      register: result

    - name: Check if barcodebuddy docker container is running
      ansible.builtin.assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
