---
- name: Prepare
  hosts: all
  tasks:
    - name: Install docker python module
      community.general.pipx:
        name: "{{ item }}"
      with_items:
        - docker
        - urllib3<2

    - name: Create a dummy gitea config directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      with_items:
        - "{{ gitea_data_directory }}/gitea/gitea/conf"

    - name: Create a dummy gitea config file
      ansible.builtin.file:
        path: "{{ gitea_data_directory }}/gitea/gitea/conf/app.ini"
        state: touch
