---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        ansible.builtin.file: ../../defaults/main.yml

    - name: Try and stop and remove Cloudcmd
      community.docker.docker_container:
        name: "{{ cloudcmd_container_name }}"
        state: absent
      register: result

    - name: Check Cloudcmd is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
