---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get plex container state
      community.docker.docker_container:
        name: "{{ plex_container_name }}"
      register: result

    - name: Get plex autoscan container state
      community.docker.docker_container:
        name: "{{ plex_autoscan_container_name }}"
      register: result_autoscan

    - name: Check if plex containers are running
      ansible.builtin.assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
          - result_autoscan.container['State']['Status'] == "running"
          - result_autoscan.container['State']['Restarting'] == false
