---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get mmp db container state
      community.docker.docker_container:
        name: "{{ mmp_db_container_name }}"
      register: result_db

    - name: Get mmp container state
      community.docker.docker_container:
        name: "{{ mmp_container_name }}"
      register: result

    - name: Check if mmp containers are running
      ansible.builtin.assert:
        that:
          - result_db.container['State']['Status'] == "running"
          - result_db.container['State']['Restarting'] == false
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
