---
- name: Prepare localhost
  hosts: localhost
  tasks:
    - name: Install jmespath
      community.general.pipx:
        name: jmespath

- name: Prepare instance
  hosts: all
  tasks:
    - name: Install docker python module
      community.general.pipx:
        name: "{{ item }}"
      with_items:
        - docker
        - urllib3<2
