---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: main/requirements.yml
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp:rw
    privileged: true
    pre_build_image: true
provisioner:
  inventory:
    group_vars:
      all:
        openldap_enabled: true
        openldap_data_directory: "/tmp/openldap"
  playbooks:
    prepare: prepare.yml
