{
 "title": "Proxmox pve2  - Hosts IPMI",
 "description": "Proxmox Host IPMI Dashboard using the Telegraf IPMI plugin",
 "tags": [
  "IPMI",
  "Proxmox"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "serveripmi",
    "label": "Server IPMI",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"anarion\",\r\n  tag: \"server\"\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "pve2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"cpu_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"CPU Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "cpu_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"system_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"System Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "system_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"peripheral_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Peripheral Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Peripheral Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "peripheral_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"dimma2_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Dimm A2 Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DIMMA2 Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "dimma2_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"dimmb2_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Dimm B2 Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DIMMB2 Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "dimmb2_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vrmab_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Vrmab Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VRMCPU Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vrmcpu_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vrmcpu_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Vrmcpu Temp\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VRMAB Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vrmab_temp" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"fan1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"rpm\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"FAN1\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FAN3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fan3" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"fan2\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"rpm\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"FAN2\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FAN4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fan4" }
     ]
    }
   ]
  },
  {
   "title": "Temperature in Celsius",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature in Celsius (°C)" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"cpu_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"CPU\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "cpu_temp" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"system_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"System\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "dimma1_temp" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"dimma2_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"DIMM A2\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "dimma2_temp" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"dimmb2_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"DIMM B2\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "dimmb1_temp" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"peripheral_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Peripheral\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "dimmb2_temp" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vrmab_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Vrmab\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "mb_10g_temp" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vrmcpu_temp\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"Vrmcpu\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "peripheral_temp" }
     ]
    }
   ]
  },
  {
   "title": "Internal System Voltages (V)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "volt", "label": "Voltage (V)" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"12v\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"12V\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "12v" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"3.3vcc\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"3.3VCC\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "3.3vcc" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"5vcc\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"5VCC\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "5vcc" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vbat\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VBat\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vbat" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vdd_33_stby\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VDD 3.3 STBY\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vdd_core_run" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vdd_5_dual\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VDD 5 DUAL\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vdd_mem_ab_sus" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vdd_core_run\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VDD Core Run\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vdd_5_dual" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vdd_mem_ab_sus\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VDD Mem AB Sus\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vdd_33_stby" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vdd_soc_dual\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VDD Soc Dual\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vdd_soc_run" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"${serveripmi}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vdd_soc_run\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"volts\")\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:\"VDD Soc Run\"}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.2.12" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "vdd_soc_daul" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kasa_online==1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_voltage_mv\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_voltage_mv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Draw",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kasa_relay_state==1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_current_ma\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_current_ma" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kasa_power_load)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_power_mw\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_power_mw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Power Current Year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_total_wh\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_total_wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Watts per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": "Power",
     "expr": "sum_over_time(kasa_power_load[1h]) /240",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{alias}}",
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_power_mw\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_power_mw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "alias": "Current",
     "expr": "sum(kasa_current)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total",
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_current_ma\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_current_ma" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage in time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    {
     "alias": "Voltage",
     "expr": "increase(kasa_power_total[24h])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{alias}}",
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"serverPower_smartplug\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"emeter_get_realtime_voltage_mv\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"anarion-nas\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_voltage_mv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Voltage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "HPE iLO v2.0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Inlet Ambient" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "01-inlet_ambient" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU Temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "02-cpu" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "P1 DIMM 1-2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "03-p1_dimm_1-2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Chipset" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "05-chipset" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Chipset Zone" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "06-chipset_zone" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "iLO Zone" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "09-ilo_zone" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VR P1 Zone" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "07-vr_p1_zone" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sys Exhaust" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "192.168.1.60" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "12-sys_exhaust" }
     ]
    }
   ]
  },
  {
   "title": "Temperature in Celsius",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature in Celsius (°C)" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "01-inlet_ambient" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "02-cpu" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "03-p1_dimm_1-2" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "05-chipset" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "06-chipset_zone" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "07-vr_p1_zone" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "09-ilo_zone" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "11-pci_1_zone" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$serveripmi$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "12-sys_exhaust" }
     ]
    }
   ]
  }
 ]
}