{
 "title": "Server Power & Climate",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_energy\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_energy\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kasa_online==1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_voltage_mv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kasa_power_load)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_power_mw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Draw",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "count(kasa_relay_state==1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_current_ma" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kasa_power_load[24h])) /240 /1000",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total",
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_energy\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_energy\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "emeter_get_realtime_total_wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Server Power Draw",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Current",
     "expr": "sum(kasa_current)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total",
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_current_ma" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage in time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Voltage",
     "expr": "increase(kasa_power_total[24h])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{alias}}",
     "measurement": "serverPower_smartplug",
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_power_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_power_power\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "emeter_get_realtime_voltage_mv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Voltage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Room Climate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_room_temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_room_temperature\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_room_temperature\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"anarion\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.server_room_humidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"server_room_humidity\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"server_room_humidity\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"HA\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}