---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      include_vars:
        file: ../../defaults/main.yml

    - name: Get krusader container state
      docker_container_info:
        name: "{{ krusader_container_name }}"
      register: result

    - name: Check if krusader docker container is running
      assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
