---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove squirrel mongo
      community.docker.docker_container:
        name: "{{ squirrel_mongo_container_name }}"
        state: absent
      register: result_mongo

    - name: Try and stop and remove squirrel redis
      community.docker.docker_container:
        name: "{{ squirrel_redis_container_name }}"
        state: absent
      register: result_redis

    - name: Try and stop and remove squirrel
      community.docker.docker_container:
        name: "{{ squirrel_container_name }}"
        state: absent
      register: result

    - name: Check if squirrel is stopped
      ansible.builtin.assert:
        that:
          - not result_mongo.changed
          - not result_redis.changed
          - not result.changed
