---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get squirrel mongo container state
      community.docker.docker_container:
        name: "{{ squirrel_mongo_container_name }}"
      register: result_mongo

    - name: Get squirrel redis container state
      community.docker.docker_container:
        name: "{{ squirrel_redis_container_name }}"
      register: result_redis

    - name: Get squirrel container state
      community.docker.docker_container:
        name: "{{ squirrel_container_name }}"
      register: result

    - name: Check if squirrel containers are running
      ansible.builtin.assert:
        that:
          - result_mongo.container['State']['Status'] == "running"
          - result_mongo.container['State']['Restarting'] == false
          - result_redis.container['State']['Status'] == "running"
          - result_redis.container['State']['Restarting'] == false
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
