---
name: Molecule

# Controls when the action will run.
on:
  push:
    branches:
      - "add_rclone"
  workflow_dispatch:

jobs:
  # generate-matrix:
  #   name: Generate test matrix
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Generate Test Matrix
  #       id: set-matrix
  #       shell: bash
  #       run: "tests/github-test-matrix.sh"

  test:
    # name: "Test ${{ matrix.role }}"
    name: "Test Rclone"
    # needs: generate-matrix
    runs-on: ubuntu-latest
    # strategy:
    #     matrix:
    #         role: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Check init system
        run: ps -p 1 -o comm=
      - name: Install system dependencies
        run: |
          sudo apt update \
          && sudo apt install -y python3-pip libssl-dev \
          && python3 -m pip install docker molecule ansible "molecule-plugins[docker]" \
          && echo "$HOME/.local/bin" >> $GITHUB_PATH
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
      - name: Validate that ansible works
        run: ansible --version
      - name: Validate that molecule works
        run: molecule --version
      - name: Install requirements
        run: ansible-galaxy install -r requirements.yml
      - name: Check user
        run: id -u
      - name: Check pwd
        run: pwd
      - name: Check /tmp
        run: ls -al /tmp
      - name: Enter target dir
        run: cd ./roles/rclone
      - name: Check molecule create
        run: |
          cd ./roles/rclone \
          && molecule --debug -vvvv -c ../../tests/molecule/base.yml create
      - name: Check molecule list
        run: |
          cd ./roles/rclone \
          && molecule --debug -vvvv -c ../../tests/molecule/base.yml list
      - name: Run tests
        run: |
          cd ./roles/rclone \
          && molecule --debug -vvvv -c ../../tests/molecule/base.yml test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
